# Introduction to Julia
<table>
<tr>
<td> <a href="http://julialang.org"><img src="figures/julia.jpg" alt="Julia" style="width: 500px;"/></a></td>
</tr></table>

Jean PAUPHILET, MIT ORC

This notebook is an introduction to the **Julia** language and its commonly used IJulia/Jupyter notebook interface. It is based on material developed by Miles Lubin and Sebastien Martin of the MIT Operations Research Center, as well as online [open-source material](http://ucidatascienceinitiative.github.io/IntroToJulia/Html/WhyJulia).

This is a broad overview of Julia and Jupyter, with many links to more specific, thorough material. We hope readers will use this resource as a reference.

## Why Julia?

Quoting the [Julia website](http://julialang.org):
> Julia is a **high-level**, **high-performance** **dynamic** programming language for **technical computing**, with syntax that is familiar to users of other technical computing environments. It provides a sophisticated compiler, distributed parallel execution, numerical accuracy, and an extensive mathematical function library.

A **high-level** language:

- Easy to use and learn, with a similar syntax to Python/Matlab. 
- It is possible to do complicated computations quickly.

For example, Solving $Ax = b$ with 
$A = \begin{pmatrix}
 1 & 2 & 3\\ 
 2 & 1 & 2\\ 
 3 & 2 & 1
\end{pmatrix}$
and $b = \begin{pmatrix}
 1 \\ 
 1 \\ 
 1 
\end{pmatrix}$
is as simple as:

In [1]:
A = [1 2 3
     2 1 2
     3 2 1]

b = [1,1,1]
A\b

3-element Array{Float64,1}:
  0.25
 -0.0 
  0.25

A **dynamic** language:

- Julia is, like Python, Matlab or R, a dynamic language: you can interact with the language without the need to compile your code. Static or compiled languages, like C or Fortran, are more complicated to use but generally faster, and thus used when there is a need for time-efficient computations. 

- Two-language approach: use high level languages for research and scripting, then translate the final result into a static language for performance.

A **high-performance** language:
- Julia is fast. Thanks to _multiple dispatch_, a strong _type system_, and _just-in-time compilation_, it can reach performance comparable to C and Fortran.
<a href="http://nbviewer.jupyter.org/url/julialang.org/benchmarks/benchmarks.ipynb"><img src="figures/Julia-benchmarks.png" alt="Julia" style="width: 1500px;"/></a>

A **vivid** open-source community:
- Julia is among the top 10 languages on Github, measured by stars and forks.
- A lot of exciting projects to build a first-class language for ML/AI (data with missing values, GPU support, numeric differenciation,...)
<img src="figures/stars.png" alt="Julia" style="width: 1500px;"/>

## Jupyter/IJulia notebook basics
For this session, we will use Julia through a Jupyter notebook, a useful tool (originally for Python) made available to Julia by the IJulia project.

### What is a Jupyter Notebook?
- Jupyter notebooks are **documents** (like a Word document) that can contain and run code.
- They were originally created for Python as part of the IPython project, and adapted for Julia by the **IJulia** project.
- They are very useful to **prototype**, draw **plots**, or even for teaching material like this one.
- The document relies only on a modern browser for rendering, and can easily be **shared**.

### Installing IJulia and loading this notebook
Once Julia is installed, start julia and just run the following command to install the `IJulia` package (you did this on the pre-assignment).
```jl
Pkg.install("IJulia")
```
This should work on its own. If there is any issue, check out the [IJulia website](https://github.com/JuliaLang/IJulia.jl).

Once IJulia is installed, go to the notebook file (_.ipynb_) directory. Then you can 
- either start julia and run:
```jl
using IJulia
notebook()
```
- or run directly in command line 
```
jupyter notebook
```
A webpage should open automatically, just click on the notebook to load it.

### Navigating the notebook

- Click `Help -> User Interface Tour` for a guided tour of the interface.
- Each notebook is composed of **cells**, that either contain code or text (`Markdown`).
- You can edit the content of a cell by double-clicking on it (_Edit Mode_).

When you are not editing a cell, you are in _Command mode_ and can edit the structure of the notebook (cells, name, options...)

- Create a cell by:
    - Clicking `Insert -> Insert Cell`
    - Pressing `a` or `b` in Command Mode
    - Pressing `Alt+Enter` in Edit Mode
- Delete a cell by:
    - Clicking `Edit -> Delete Cell`
    - Pressing `dd`
- Execute a cell by:
    - Clicking `Cell -> Run`
    - Pressing `Ctrl+Enter`

Other functions:
- Undo last text edit with `Ctrl+z` in Edit Mode
- Undo last cell manipulation with `z` in Command Mode
- Save notebook with `Ctrl+s` in Edit Mode
- Save notebook with `s` in Command Mode

Though notebooks rely on your browser to work, they do not require an internet connection (except for math rendering).

### Get comfortable with the notebook
Notebooks are designed to not be fragile. If you try to close a notebook with unsaved changes, the browser will warn you.

Try the following exercises:

>**\[Exercise\]**: Close/open

>1. Save the notebook
>2. Copy the address
>3. Close the tab
>4. Paste the address into a new tab (or re-open the last closed tab with `Ctrl+Shift+T` on Chrome)

>_The document is still there, and the Julia kernel is still alive! Nothing is lost._

>**\[Exercise\]**: Zoom

>Try changing the magnification of the web page (`Ctrl+, Ctrl-` on Chrome).

>_Text and math scale well (so do graphics if you use an SVG or PDF backend)._

>**\[Exercise\]**: MathJax
>1. Create a new cell, and select the type `Markdown` (or press `m`)
>2. Type an opening \$, your favorite mathematical expression, and a closing \$.
>3. Run the cell to render the $\LaTeX$ expression.
>4. Right-click the rendered expression.

### Advanced Jupyter notebooks' usage (Bonus)
Jupyter notebooks have a lot of interesting hidden functionalities!

**Github and sharing**

If you save your .ipynb notebook file in a .git project, hosted on Github, you can easily visualize and share it online (in non-interactive mode).

For example, this notebook is available at https://github.com/sebmart/intro-julia-jupyter/blob/master/intro-julia-jupyter.ipynb

You can also use [Gist](https://gist.github.com) and [nbviewer](http://nbviewer.jupyter.org) to quickly share a notebook (for example to your advisor) without creating a git repo.

**Converting your notebook**

Jupyter notebooks are a popular format that can be converted to a variety of types of documents, depending on your needs:
- Latex
- HTML
- PDF
- Slides with Reveal.JS (used to present this notebook!)
- Markdown ...

These conversions use the [`nbconvert`](https://github.com/jupyter/nbconvert) command.

**Remote computing**

The Notebook system is a web interface. Notebooks can be run on another computer. This is useful if you want your code to run on a more powerful remote machine.

[Port-forwarding](https://help.ubuntu.com/community/SSH/OpenSSH/PortForwarding) through SSH is a good start for this.

**Advanced Markdown**

Jupyter text cells use Markdown for formatting. Markdown is an easy to use formatting language (a little like HTML or LaTeX in more simple). You can use the text of this notebook as an example, or learn more [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

Jupyter uses _Github flavored Markdown_, and is particularly good at displaying math and colored code. You can even include a video!

## Coding in Julia

This section is a brief introduction to Julia. It is not a comprehensive tutorial but more a _taste_ of the language for those who do not know it, and a showcase of cool features for those who already know Julia.

Very good [tutorials](http://julialang.org/learning/) are available online and in books if you are interested in learning the language.

### Basic use
Julia, as a dynamic language, can simply be used as a calculator:

In [2]:
1+1

2

In [3]:
sin(exp(2*pi)+sqrt(3))

-0.01136232398070678

The building blocs of Julia code are variables:

In [4]:
a = 1
b = 2
# This is a comment 
c = a^2 + b^3 

9

Julia supports the common `if`, `while` and `for` structures:

In [5]:
if c >= 10
    print("Hello")
else
    print("World")
end

World

In [6]:
i = 1
while i <= 5
    println("Why, hello!") # Print with a new line
    i += 1
end

Why, hello!
Why, hello!
Why, hello!
Why, hello!
Why, hello!


In [7]:
for i = 1:3
    print("$i banana") # '$' can be used to insert variables into text
    if i>1
        print("s")
    end
    println() # Just a new line
end

1 banana
2 bananas
3 bananas


**Do not worry about writing loops**: in Julia, they are as fast as writing vectorized code, and sometimes faster!

**Arrays** (list of numbers) are at the core of research computing and Julia's arrays are extremely optimized.

In [8]:
myList = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

Array indexing starts with 1 in Julia:

In [9]:
myList[1]

1

In [10]:
myList[3] = 4 
myList

3-element Array{Int64,1}:
 1
 2
 4

A 2-dimensional array is a Matrix

In [11]:
A = [1 2 3
     2 1 2
     3 2 1]

A = [1 2 3; 2 1 2; 3 2 1] #same thing

3×3 Array{Int64,2}:
 1  2  3
 2  1  2
 3  2  1

Matrices can be multiplied, inverted...

In [12]:
A^-1 #inverse

A^2 * A^-1

3×3 Array{Float64,2}:
 1.0  2.0  3.0
 2.0  1.0  2.0
 3.0  2.0  1.0

In [13]:
A*[1,2,3]

3-element Array{Int64,1}:
 14
 10
 10

Component-wise operations can be obtained by adding a '.' in front of the operator. See the difference for instance between:

In [14]:
Id = [1 0 0; 0 1 0; 0 0 1]
A .+ Id

3×3 Array{Int64,2}:
 2  2  3
 2  2  2
 3  2  2

and

In [15]:
A + Id

3×3 Array{Int64,2}:
 2  2  3
 2  2  2
 3  2  2

(Well there is none because matrix addition is component-wise)

In [16]:
A .* Id

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

and

In [17]:
A * Id

3×3 Array{Int64,2}:
 1  2  3
 2  1  2
 3  2  1

Let's try a quick exercise!

> **[Exercise]** A random variable $X\sim\text{Bin}(n,p)$ is defined as the number of successes in $n$ trials where each trial has a success probability $p$. For example, if $X=\text{Bin}(10,0.5)$, then $X$ is the number of coin flips that turn up heads in 10 flips of a fair coin.

> Using only the function `rand()`, which generates a uniformly random number between 0 and 1, write a function `binomial_rv(n,p)` that outputs a single draw of a binomial random variable with parameters `n` and `p`.

In [20]:
function binomial_rv(n, p)
    sum(1*(rand(n) .< p))
end
binomial_rv(10,0.5)

4

### Just-in-time compilation

We mentioned earlier that one of the reasons Julia is fast is _just-in-time_ compilation. This means that right before a function is executed, Julia compiles it and optimizes it. Function compilations are also cached for future use.

In [21]:
function countTo(n)
    count = 0
    for i = 1:n
        count += 1
    end
    return count
end
println("First use: slow like a dynamic language")
@time countTo(10_000_000) #the @time macro is useful to track computational time and memory usage
println("Second use: compiled and optimized automatically")
@time countTo(10_000_000);

First use: slow like a dynamic language
  0.006647 seconds (13.03 k allocations: 701.250 KiB)
Second use: compiled and optimized automatically
  0.000002 seconds (5 allocations: 176 bytes)


### Type stability

Other interpreted languages have just-in-time compilers (e.g. Python). Why is Julia better?

**Types:** Everything has a type in Julia

In [22]:
typeof(1)

Int64

In [23]:
typeof(1.5)

Float64

In [24]:
typeof("abc")

String

Type stability is the idea that there is only one possible type which can be output by a method. For example, the reasonable type to output from `*(::Int64,::Int64)` is an `Int64`. No matter what you give it, it will spit out an `Int64`.

This is called **[multiple dispatch](https://en.wikipedia.org/wiki/Multiple_dispatch)** : the `*` operator calls a different method depending on the types that it sees.

In [25]:
1//2 # fraction in Julia

1//2

In [26]:
typeof(1//2)

Rational{Int64}

In [27]:
(1//2)*(1//2)

1//4

In [28]:
(0.5)*(0.5) # The same function gives different results depending on the type

0.25

In [29]:
(im)*(im) # This also works with complex numbers

-1 + 0im

In [30]:
function myFunction(x)
    println("Default output")
end

function myFunction(x::Int) # only called when x is an integer
    println("You gave me an integer!")
end

myFunction(1.0)
myFunction(1)
myFunction("ORC")

Default output
You gave me an integer!
Default output


#### How does type stability help?

To explore the power of Julia's type-stable system, we will use code introspection macros to see what the code actually compiles to. Let's look at the code in LLVM, a portable assembly language:

In [31]:
@code_llvm ^(2,5)


; Function ^
; Location: intfuncs.jl:220
define i64 @"julia_^_35873"(i64, i64) {
top:
  %2 = call i64 @julia_power_by_squaring_27457(i64 %0, i64 %1)
  ret i64 %2
}


The code above is short and sweet: it multiplies the two numbers and returns the result. It turns out that the compiled code is _the same_ as the compiled version of the same code written in C or Fortran.

_Question_: in what cases does the code compile to something as efficient as C/Fortran?

_Answer_: **type-stability**. If a function is type-stable, then the compiler can know what the type will be at all points in the function and smartly optimize it to the same assembly as C/Fortran. If it is not type-stable, Julia has to add expensive "boxing" to ensure types are found/known before operations are performed.

## Fun functionalities

Julia has a lot of nice functionalities for you to discover!

#### List comprehension (similar to Python)

In [32]:
[i^2 for i in 1:10 if i%2 == 0] # list comprehensions (similar to Python)

5-element Array{Int64,1}:
   4
  16
  36
  64
 100

#### Support for unicode characters ($\LaTeX$ syntax)
You can use unicode characters as part of variables and function names in Julia. Some of them are already defined Julia constants and functions
> Try to type `\pi<TAB>` in a cell.

In [33]:
π

π = 3.1415926535897...

In [34]:
"carrot" ∈ ["potato", "tomato", "carrot"]

true

In [35]:
η = rand()
println(η)
if η >= 0.1 && η < .5 #check if η ∈ [.1, .5)
    println("In")
else 
    println("Out")
end

0.32207950528848817
In


In [36]:
√2

1.4142135623730951

In [37]:
sumEvenSquares = sum(i^2 for i in 1:10 if i%2 == 0) # summing over an iterator

220

### Package manager

Julia has a package manager to quickly download, install, update and uninstall new tools (_packages_)

You can enter use the package manager in two ways:
- as the 'Pkg' package 
- by pressing the ']' key

Compare those two syntaxes

In [38]:
] add DataFrames

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  99.9 %0.0 %13.5 %>                             ]  27.1 %Fetching: [=================>                       ]  40.6 %             ]  66.5 % [=================================>       ]  80.0 % Resolving package versions...
 Installed SoftGlobalScope ─────── v1.0.8
 Installed JSExpr ──────────────── v0.5.0
 Installed TableTraits ─────────── v0.4.1
 Installed CMake ───────────────── v1.1.1
 Installed NLSolversBase ───────── v7.1.2
 Installed FunctionalCollections ─ v0.5.0
 Installed ImageFiltering ──────── v0.5.2
 Installed Interpolations ──────── v0.11.1
 Installed Rotations ───────────── v0.9.2
 Installed WebSockets ──────────── v1.2.0
 Installed StaticArrays ────────── v0.10.2
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [631607c0] ↑ C

and

In [39]:
using Pkg
Pkg.add("DataFrames")

 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]


By default, Julia has many built-in packages. And **over 1,900 registered packages**!

** LinearAlgebra **

In [40]:
using LinearAlgebra

In [41]:
LinearAlgebra.Matrix(1.0LinearAlgebra.I, 3, 3) #Defines the identity matrix

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [42]:
eigenValues, eigenVectors = LinearAlgebra.eigen(A)
eigenValues

3-element Array{Float64,1}:
 -2.0               
 -0.7015621187164252
  5.701562118716413 

** Statistics **

In [43]:
using Statistics
Statistics.mean(A)

1.8888888888888888

In [44]:
Statistics.median(A)

2.0

** Random **

In [45]:
using Random

In [46]:
Random.seed!(10)

MersenneTwister(UInt32[0x0000000a], Random.DSFMT.DSFMT_state(Int32[1007524736, 1073256705, 415953332, 1072893275, -601364280, 1073193666, -1335760268, 1072926448, 1521827180, 1073499520  …  -439825479, 1072978026, -411693740, 1073111955, -1611334130, 1963385220, 236575170, -789052601, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x0000000000

In [47]:
Random.randperm(5)

5-element Array{Int64,1}:
 5
 1
 4
 2
 3

In [48]:
Random.shuffle(1:5)

5-element Array{Int64,1}:
 5
 1
 2
 3
 4

Use `?` to get the documentation of a function

In [49]:
?eigen

search: eigen eigen! Eigen eigenValues eigenVectors GeneralizedEigen eigvecs



```
eigen(A; permute::Bool=true, scale::Bool=true) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an `Eigen` factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

For general nonsymmetric matrices it is possible to specify how the matrix is balanced before the eigenvector calculation. The option `permute=true` permutes the matrix to become closer to upper triangular, and `scale=true` scales the matrix by its diagonal elements to make rows and columns more equal in norm. The default is `true` for both options.

# Examples

```jldoctest
julia> F = eigen([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])
Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
3-element Array{Float64,1}:
  1.0
  3.0
 18.0
eigenvectors:
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> F.values
3-element Array{Float64,1}:
  1.0
  3.0
 18.0

julia> F.vectors
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> vals, vecs = F; # destructuring via iteration

julia> vals == F.values && vecs == F.vectors
true
```

---

```
eigen(A, B) -> GeneralizedEigen
```

Computes the generalized eigenvalue decomposition of `A` and `B`, returning a `GeneralizedEigen` factorization object `F` which contains the generalized eigenvalues in `F.values` and the generalized eigenvectors in the columns of the matrix `F.vectors`. (The `k`th generalized eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

# Examples

```jldoctest
julia> A = [1 0; 0 -1]
2×2 Array{Int64,2}:
 1   0
 0  -1

julia> B = [0 1; 1 0]
2×2 Array{Int64,2}:
 0  1
 1  0

julia> F = eigen(A, B);

julia> F.values
2-element Array{Complex{Float64},1}:
 0.0 + 1.0im
 0.0 - 1.0im

julia> F.vectors
2×2 Array{Complex{Float64},2}:
  0.0-1.0im   0.0+1.0im
 -1.0-0.0im  -1.0+0.0im

julia> vals, vecs = F; # destructuring via iteration

julia> vals == F.values && vecs == F.vectors
true
```

---

```
eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, irange::UnitRange) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an `Eigen` factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

The `UnitRange` `irange` specifies indices of the sorted eigenvalues to search for.

!!! note
    If `irange` is not `1:n`, where `n` is the dimension of `A`, then the returned factorization will be a *truncated* factorization.


---

```
eigen(A::Union{SymTridiagonal, Hermitian, Symmetric}, vl::Real, vu::Real) -> Eigen
```

Computes the eigenvalue decomposition of `A`, returning an `Eigen` factorization object `F` which contains the eigenvalues in `F.values` and the eigenvectors in the columns of the matrix `F.vectors`. (The `k`th eigenvector can be obtained from the slice `F.vectors[:, k]`.)

Iterating the decomposition produces the components `F.values` and `F.vectors`.

The following functions are available for `Eigen` objects: [`inv`](@ref), [`det`](@ref), and [`isposdef`](@ref).

`vl` is the lower bound of the window of eigenvalues to search for, and `vu` is the upper bound.

!!! note
    If [`vl`, `vu`] does not contain all eigenvalues of `A`, then the returned factorization will be a *truncated* factorization.



Use tab-completion to auto-complete functions and variables names: try ``myF<TAB>``:

In [50]:
myFunction
factorial

factorial (generic function with 7 methods)

The ``methods`` function lists all of the different implementations of a function depending on the input types.
Click on the link to see the Julia source code.

In [51]:
methods(sin)

# 12 methods for generic function "sin":
[1] sin(x::BigFloat) in Base.MPFR at mpfr.jl:683
[2] sin(::Missing) in Base.Math at math.jl:1070
[3] sin(a::Complex{Float16}) in Base.Math at math.jl:1019
[4] sin(a::Float16) in Base.Math at math.jl:1018
[5] sin(z::Complex{T}) where T in Base at complex.jl:760
[6] sin(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:30
[7] sin(x::Real) in Base.Math at special/trig.jl:53
[8] sin(A::Hermitian{#s560,S} where S<:(AbstractArray{#s561,2} where #s561<:#s560) where #s560<:Complex) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/symmetric.jl:720
[9] sin(A::Union{Hermitian{#s561,S}, Symmetric{#s561,S}} where S where #s561<:Real) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/symmetric.jl:716
[10] sin(D::Diagonal) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/diagonal.jl:424
[11] sin(A::AbstractArray{#s561,2} where #s561<:Real) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/dense.jl:770
[12] sin(A::AbstractArray{#s561,2} where #s561<:Complex) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/LinearAlgebra/src/dense.jl:777

### Other Julia functionalities (Bonus)
We only presented a small subset of Julia functionalities. We list here of few interesting things you may not know.

**Using the command line from Julia**

You can run bash commands directly from Julia by starting the command with a semicolon: `;`

In [52]:
;ls

1-intro-julia-jupyter-old.ipynb
1-julia-basics-complete.ipynb
1-julia-basics-slides.slides.html
1-julia-basics.ipynb
2-julia-data-case.ipynb
3-julia-jump-case.ipynb
JuMP - Integer Programming (complete).ipynb
JuMP - Integer Programming.ipynb
README.md
data
experiment
figures


**Juno**

Julia has a very nice and powerful text editor, [_Juno_](http://junolab.org), that is built on [Atom](https://atom.io). It is very similar to the Matlab interface or RStudio. Functionalities include:
- Autocomplete
- Integrated Plotting
- Debugging, Manual, ...

It is better suited for serious projects with several files, when an IJulia notebook is not enough.

**Advanced Julia functionalities**
Julia is a state-of-the-art programming language, with lots of useful functionalities, including:
- [Powerful Macros](https://docs.julialang.org/en/v1/manual/metaprogramming/#Metaprogramming-1) (meta-programming)
- [Code testing](https://docs.julialang.org/en/v1/stdlib/Test/#Basic-Unit-Tests-1)
- [User-defined types](https://docs.julialang.org/en/v1/manual/types/#man-types-1), that are as fast as built-in ones.
- [Package creation](https://docs.julialang.org/en/v1/stdlib/Pkg/#Creating-your-own-packages-1)

** Interesting Packages **
Using the Package eco-system, there is almost nothing you cannot achieve:

- Advanced Plotting   with [**Plots.jl**](https://juliaplots.github.io). Functionalities include 3D-plots, animated plots, stats plots, home-made plot "recipes" ...
- Call any python code using [**PyCall.jl**](https://github.com/JuliaPy/PyCall.jl), R code using [**RCall.jl**](https://github.com/JuliaInterop/RCall.jl)
- Save and load your variables or environment to a file with [**JLD2.jl**](https://github.com/JuliaIO/JLD2.jl)
- Advanced graphs/networks algorithms with [**LightGraphs.jl**](https://github.com/JuliaGraphs/LightGraphs.jl)
- Applications in [**Finance**](https://github.com/JuliaQuant), [**Biology**](https://github.com/BioJulia/Bio.jl), [**Stats and Machine Learning**](http://juliastats.github.io), [**Optimization**](http://www.juliaopt.org) (including the great [**JuMP**](https://github.com/JuliaOpt/JuMP.jl) package!)

And a lot more in the over 1,900 registered packages!