# Introduction to JuMP

In this session, we will explore the basic functionalities of JuMP

## Step 1: Read the  data 
We will work on a credit report data set from UCI ML repository

In [32]:
using DataFrames, CSV

In [33]:
df = CSV.read("data/german.data.clean.txt")

1000×21 DataFrame. Omitted printing of 16 columns
│ Row  │ CheckingAccount │ Duration │ CreditHistory │ Purpose   │ Amount │
│      │ String⍰         │ Int64⍰   │ String⍰       │ String⍰   │ Int64⍰ │
├──────┼─────────────────┼──────────┼───────────────┼───────────┼────────┤
│ 1    │ 0DM             │ 6        │ Mediocre      │ RadioTV   │ 1169   │
│ 2    │ 0-200DM         │ 48       │ Average       │ RadioTV   │ 5951   │
│ 3    │ None            │ 12       │ Mediocre      │ Education │ 2096   │
│ 4    │ 0DM             │ 42       │ Average       │ Furniture │ 7882   │
│ 5    │ 0DM             │ 24       │ BelowAverage  │ NewCar    │ 4870   │
│ 6    │ None            │ 36       │ Average       │ Education │ 9055   │
│ 7    │ None            │ 24       │ Average       │ Furniture │ 2835   │
│ 8    │ 0-200DM         │ 36       │ Average       │ UsedCar   │ 6948   │
│ 9    │ None            │ 12       │ Average       │ RadioTV   │ 3059   │
│ 10   │ 0-200DM         │ 30       │ Mediocre      │ NewCar    │ 5234   │
⋮
│ 990  │ 0-200DM         │ 24       │ Mediocre      │ RadioTV   │ 1743   │
│ 991  │ None            │ 12       │ Mediocre      │ Education │ 3565   │
│ 992  │ None            │ 15       │ Good          │ RadioTV   │ 1569   │
│ 993  │ 0DM             │ 18       │ Average       │ RadioTV   │ 1936   │
│ 994  │ 0DM             │ 36       │ Average       │ Furniture │ 3959   │
│ 995  │ None            │ 12       │ Average       │ NewCar    │ 2390   │
│ 996  │ None            │ 12       │ Average       │ Furniture │ 1736   │
│ 997  │ 0DM             │ 30       │ Average       │ UsedCar   │ 3857   │
│ 998  │ None            │ 12       │ Average       │ RadioTV   │ 804    │
│ 999  │ 0DM             │ 45       │ Average       │ RadioTV   │ 1845   │
│ 1000 │ 0-200DM         │ 45       │ Mediocre      │ UsedCar   │ 4576   │

Let us briefly look at the data

In [34]:
size(df)

(1000, 21)

In [35]:
DataFrames.describe(df)

21×8 DataFrame. Omitted printing of 4 columns
│ Row │ variable              │ mean    │ min                     │ median │
│     │ Symbol                │ Union…  │ Any                     │ Union… │
├─────┼───────────────────────┼─────────┼─────────────────────────┼────────┤
│ 1   │ CheckingAccount       │         │ 0-200DM                 │        │
│ 2   │ Duration              │ 20.903  │ 4                       │ 18.0   │
│ 3   │ CreditHistory         │         │ Average                 │        │
│ 4   │ Purpose               │         │ Appliances              │        │
│ 5   │ Amount                │ 3271.26 │ 250                     │ 2319.5 │
│ 6   │ SavingsAccount        │         │ 0-100DM                 │        │
│ 7   │ EmploymentYears       │         │ 0-1y                    │        │
│ 8   │ InstallmentRate       │ 2.973   │ 1                       │ 3.0    │
│ 9   │ PersonalStatus        │         │ FemaleDivorcedOrMarried │        │
│ 10  │ OtherDebtor           │         │ CoApplicant             │        │
│ 11  │ PresentResidenceSince │ 2.845   │ 1                       │ 3.0    │
│ 12  │ Property              │         │ Car                     │        │
│ 13  │ Age                   │ 35.546  │ 19                      │ 33.0   │
│ 14  │ InstallmentPlan       │         │ Bank                    │        │
│ 15  │ Housing               │         │ Free                    │        │
│ 16  │ CreditNumber          │ 1.407   │ 1                       │ 1.0    │
│ 17  │ Job                   │         │ Management              │        │
│ 18  │ LiablePeople          │ 1.155   │ 1                       │ 1.0    │
│ 19  │ Telephone             │         │ None                    │        │
│ 20  │ ForeignWorker         │         │ No                      │        │
│ 21  │ y                     │ 1.3     │ 1                       │ 1.0    │

**Side note: ** You can also do SQL-like joins in Julia

In [36]:
stupidTable = DataFrames.DataFrame(Purpose=["Retraining", "RadioTV", "Appliances", "UsedCar", "NewCar"], 
    ForWork=["Yes", "No", "No", "Maybe", "Maybe"])

5×2 DataFrame
│ Row │ Purpose    │ ForWork │
│     │ String     │ String  │
├─────┼────────────┼─────────┤
│ 1   │ Retraining │ Yes     │
│ 2   │ RadioTV    │ No      │
│ 3   │ Appliances │ No      │
│ 4   │ UsedCar    │ Maybe   │
│ 5   │ NewCar     │ Maybe   │

In [37]:
DataFrames.join(df, stupidTable, on=:Purpose)

638×22 DataFrame. Omitted printing of 17 columns
│ Row │ CheckingAccount │ Duration │ CreditHistory │ Purpose │ Amount │
│     │ String⍰         │ Int64⍰   │ String⍰       │ String⍰ │ Int64⍰ │
├─────┼─────────────────┼──────────┼───────────────┼─────────┼────────┤
│ 1   │ 0DM             │ 6        │ Mediocre      │ RadioTV │ 1169   │
│ 2   │ 0-200DM         │ 48       │ Average       │ RadioTV │ 5951   │
│ 3   │ 0DM             │ 24       │ BelowAverage  │ NewCar  │ 4870   │
│ 4   │ 0-200DM         │ 36       │ Average       │ UsedCar │ 6948   │
│ 5   │ None            │ 12       │ Average       │ RadioTV │ 3059   │
│ 6   │ 0-200DM         │ 30       │ Mediocre      │ NewCar  │ 5234   │
│ 7   │ 0-200DM         │ 12       │ Average       │ NewCar  │ 1295   │
│ 8   │ 0-200DM         │ 12       │ Average       │ RadioTV │ 1567   │
│ 9   │ 0DM             │ 24       │ Mediocre      │ NewCar  │ 1199   │
│ 10  │ 0DM             │ 15       │ Average       │ NewCar  │ 1403   │
⋮
│ 628 │ 0DM             │ 36       │ Average       │ UsedCar │ 8229   │
│ 629 │ None            │ 13       │ Average       │ RadioTV │ 1409   │
│ 630 │ 0DM             │ 24       │ Average       │ UsedCar │ 6579   │
│ 631 │ 0-200DM         │ 24       │ Mediocre      │ RadioTV │ 1743   │
│ 632 │ None            │ 15       │ Good          │ RadioTV │ 1569   │
│ 633 │ 0DM             │ 18       │ Average       │ RadioTV │ 1936   │
│ 634 │ None            │ 12       │ Average       │ NewCar  │ 2390   │
│ 635 │ 0DM             │ 30       │ Average       │ UsedCar │ 3857   │
│ 636 │ None            │ 12       │ Average       │ RadioTV │ 804    │
│ 637 │ 0DM             │ 45       │ Average       │ RadioTV │ 1845   │
│ 638 │ 0-200DM         │ 45       │ Mediocre      │ UsedCar │ 4576   │

By default joins are "inner" joins, but you can specify a kind

In [38]:
DataFrames.join(df, stupidTable, on=:Purpose, kind=:left)

1000×22 DataFrame. Omitted printing of 17 columns
│ Row  │ CheckingAccount │ Duration │ CreditHistory │ Purpose   │ Amount │
│      │ String⍰         │ Int64⍰   │ String⍰       │ String⍰   │ Int64⍰ │
├──────┼─────────────────┼──────────┼───────────────┼───────────┼────────┤
│ 1    │ 0DM             │ 6        │ Mediocre      │ RadioTV   │ 1169   │
│ 2    │ 0-200DM         │ 48       │ Average       │ RadioTV   │ 5951   │
│ 3    │ None            │ 12       │ Mediocre      │ Education │ 2096   │
│ 4    │ 0DM             │ 42       │ Average       │ Furniture │ 7882   │
│ 5    │ 0DM             │ 24       │ BelowAverage  │ NewCar    │ 4870   │
│ 6    │ None            │ 36       │ Average       │ Education │ 9055   │
│ 7    │ None            │ 24       │ Average       │ Furniture │ 2835   │
│ 8    │ 0-200DM         │ 36       │ Average       │ UsedCar   │ 6948   │
│ 9    │ None            │ 12       │ Average       │ RadioTV   │ 3059   │
│ 10   │ 0-200DM         │ 30       │ Mediocre      │ NewCar    │ 5234   │
⋮
│ 990  │ 0-200DM         │ 24       │ Mediocre      │ RadioTV   │ 1743   │
│ 991  │ None            │ 12       │ Mediocre      │ Education │ 3565   │
│ 992  │ None            │ 15       │ Good          │ RadioTV   │ 1569   │
│ 993  │ 0DM             │ 18       │ Average       │ RadioTV   │ 1936   │
│ 994  │ 0DM             │ 36       │ Average       │ Furniture │ 3959   │
│ 995  │ None            │ 12       │ Average       │ NewCar    │ 2390   │
│ 996  │ None            │ 12       │ Average       │ Furniture │ 1736   │
│ 997  │ 0DM             │ 30       │ Average       │ UsedCar   │ 3857   │
│ 998  │ None            │ 12       │ Average       │ RadioTV   │ 804    │
│ 999  │ 0DM             │ 45       │ Average       │ RadioTV   │ 1845   │
│ 1000 │ 0-200DM         │ 45       │ Mediocre      │ UsedCar   │ 4576   │

**Side note: ** Categorical variables

In [39]:
categorical_features = [:CheckingAccount, :CreditHistory, :Purpose, :SavingsAccount, :EmploymentYears, :PersonalStatus,
:OtherDebtor, :Property, :InstallmentPlan, :Housing, :Job, :Telephone, :ForeignWorker]

13-element Array{Symbol,1}:
 :CheckingAccount
 :CreditHistory  
 :Purpose        
 :SavingsAccount 
 :EmploymentYears
 :PersonalStatus 
 :OtherDebtor    
 :Property       
 :InstallmentPlan
 :Housing        
 :Job            
 :Telephone      
 :ForeignWorker  

In [40]:
DataFrames.categorical!(df, categorical_features)

1000×21 DataFrame. Omitted printing of 16 columns
│ Row  │ CheckingAccount │ Duration │ CreditHistory │ Purpose       │ Amount │
│      │ Categorical…⍰   │ Int64⍰   │ Categorical…⍰ │ Categorical…⍰ │ Int64⍰ │
├──────┼─────────────────┼──────────┼───────────────┼───────────────┼────────┤
│ 1    │ 0DM             │ 6        │ Mediocre      │ RadioTV       │ 1169   │
│ 2    │ 0-200DM         │ 48       │ Average       │ RadioTV       │ 5951   │
│ 3    │ None            │ 12       │ Mediocre      │ Education     │ 2096   │
│ 4    │ 0DM             │ 42       │ Average       │ Furniture     │ 7882   │
│ 5    │ 0DM             │ 24       │ BelowAverage  │ NewCar        │ 4870   │
│ 6    │ None            │ 36       │ Average       │ Education     │ 9055   │
│ 7    │ None            │ 24       │ Average       │ Furniture     │ 2835   │
│ 8    │ 0-200DM         │ 36       │ Average       │ UsedCar       │ 6948   │
│ 9    │ None            │ 12       │ Average       │ RadioTV       │ 3059   │
│ 10   │ 0-200DM         │ 30       │ Mediocre      │ NewCar        │ 5234   │
⋮
│ 990  │ 0-200DM         │ 24       │ Mediocre      │ RadioTV       │ 1743   │
│ 991  │ None            │ 12       │ Mediocre      │ Education     │ 3565   │
│ 992  │ None            │ 15       │ Good          │ RadioTV       │ 1569   │
│ 993  │ 0DM             │ 18       │ Average       │ RadioTV       │ 1936   │
│ 994  │ 0DM             │ 36       │ Average       │ Furniture     │ 3959   │
│ 995  │ None            │ 12       │ Average       │ NewCar        │ 2390   │
│ 996  │ None            │ 12       │ Average       │ Furniture     │ 1736   │
│ 997  │ 0DM             │ 30       │ Average       │ UsedCar       │ 3857   │
│ 998  │ None            │ 12       │ Average       │ RadioTV       │ 804    │
│ 999  │ 0DM             │ 45       │ Average       │ RadioTV       │ 1845   │
│ 1000 │ 0-200DM         │ 45       │ Mediocre      │ UsedCar       │ 4576   │

Let us look into the :CheckingAccount table

In [41]:
df[:CheckingAccount]

1000-element CategoricalArray{Union{Missing, String},1,UInt32}:
 "0DM"    
 "0-200DM"
 "None"   
 "0DM"    
 "0DM"    
 "None"   
 "None"   
 "0-200DM"
 "None"   
 "0-200DM"
 "0-200DM"
 "0DM"    
 "0-200DM"
 ⋮        
 "0DM"    
 "0-200DM"
 "None"   
 "None"   
 "0DM"    
 "0DM"    
 "None"   
 "None"   
 "0DM"    
 "None"   
 "0DM"    
 "0-200DM"

Notice the type: CategoricalArray{Union{Missing, String},1,UInt32}
This is a ** parametric type **, i.e., a type that depends on a type
- The first type (Union{Missing, String} here) refers to the type for the label names.
- The last type (UInt32 here) refers to the type used to encode the level number. By default, the categorical type can encode categorical variables with up to 32 levels. If you do not need as many levels, you can use smaller integers by compressing the data.

In [42]:
DataFrames.levels(df[:CheckingAccount])

4-element Array{String,1}:
 "0-200DM"
 "0DM"    
 "200DM+" 
 "None"   

In [43]:
DataFrames.compress(df[:CheckingAccount])

1000-element CategoricalArray{Union{Missing, String},1,UInt8}:
 "0DM"    
 "0-200DM"
 "None"   
 "0DM"    
 "0DM"    
 "None"   
 "None"   
 "0-200DM"
 "None"   
 "0-200DM"
 "0-200DM"
 "0DM"    
 "0-200DM"
 ⋮        
 "0DM"    
 "0-200DM"
 "None"   
 "None"   
 "0DM"    
 "0DM"    
 "None"   
 "None"   
 "0DM"    
 "None"   
 "0DM"    
 "0-200DM"

In [44]:
df[:CheckingAccount] = DataFrames.compress(df[:CheckingAccount])

1000-element CategoricalArray{Union{Missing, String},1,UInt8}:
 "0DM"    
 "0-200DM"
 "None"   
 "0DM"    
 "0DM"    
 "None"   
 "None"   
 "0-200DM"
 "None"   
 "0-200DM"
 "0-200DM"
 "0DM"    
 "0-200DM"
 ⋮        
 "0DM"    
 "0-200DM"
 "None"   
 "None"   
 "0DM"    
 "0DM"    
 "None"   
 "None"   
 "0DM"    
 "None"   
 "0DM"    
 "0-200DM"

## Step 2: One-hot-encoding

There is no easy way (I know of) to one-hot encode data in Julia. Hopefully, we have RCall!

In [45]:
using RCall

You need to install the R package "dummies" first. Then run the R code:

In [46]:
R"library(\"dummies\")"
R"df_onehot <- dummy.data.frame($df)"

RObject{VecSxp}
     CheckingAccount0DM CheckingAccount0-200DM CheckingAccountNone
1                     1                      0                   0
2                     0                      1                   0
3                     0                      0                   1
4                     1                      0                   0
5                     1                      0                   0
6                     0                      0                   1
7                     0                      0                   1
8                     0                      1                   0
9                     0                      0                   1
10                    0                      1                   0
11                    0                      1                   0
12                    1                      0                   0
13                    0                      1                   0
14                    1                      0

To import a R object back into julia, simply use the @rget macro

In [48]:
@rget df_onehot

1000×62 DataFrame. Omitted printing of 59 columns
│ Row  │ CheckingAccount0DM │ CheckingAccount0-200DM │ CheckingAccountNone │
│      │ Int64              │ Int64                  │ Int64               │
├──────┼────────────────────┼────────────────────────┼─────────────────────┤
│ 1    │ 1                  │ 0                      │ 0                   │
│ 2    │ 0                  │ 1                      │ 0                   │
│ 3    │ 0                  │ 0                      │ 1                   │
│ 4    │ 1                  │ 0                      │ 0                   │
│ 5    │ 1                  │ 0                      │ 0                   │
│ 6    │ 0                  │ 0                      │ 1                   │
│ 7    │ 0                  │ 0                      │ 1                   │
│ 8    │ 0                  │ 1                      │ 0                   │
│ 9    │ 0                  │ 0                      │ 1                   │
│ 10   │ 0                  │ 1                      │ 0                   │
⋮
│ 990  │ 0                  │ 1                      │ 0                   │
│ 991  │ 0                  │ 0                      │ 1                   │
│ 992  │ 0                  │ 0                      │ 1                   │
│ 993  │ 1                  │ 0                      │ 0                   │
│ 994  │ 1                  │ 0                      │ 0                   │
│ 995  │ 0                  │ 0                      │ 1                   │
│ 996  │ 0                  │ 0                      │ 1                   │
│ 997  │ 1                  │ 0                      │ 0                   │
│ 998  │ 0                  │ 0                      │ 1                   │
│ 999  │ 1                  │ 0                      │ 0                   │
│ 1000 │ 0                  │ 1                      │ 0                   │

In [49]:
CSV.write("data/german.data.onehot.txt", df_onehot)

"german.data.onehot.txt"

In [50]:
df_onehot = CSV.read("data/german.data.onehot.txt")

1000×62 DataFrame. Omitted printing of 59 columns
│ Row  │ CheckingAccount0DM │ CheckingAccount0-200DM │ CheckingAccountNone │
│      │ Int64⍰             │ Union{Missing, Int64}  │ Int64⍰              │
├──────┼────────────────────┼────────────────────────┼─────────────────────┤
│ 1    │ 1                  │ 0                      │ 0                   │
│ 2    │ 0                  │ 1                      │ 0                   │
│ 3    │ 0                  │ 0                      │ 1                   │
│ 4    │ 1                  │ 0                      │ 0                   │
│ 5    │ 1                  │ 0                      │ 0                   │
│ 6    │ 0                  │ 0                      │ 1                   │
│ 7    │ 0                  │ 0                      │ 1                   │
│ 8    │ 0                  │ 1                      │ 0                   │
│ 9    │ 0                  │ 0                      │ 1                   │
│ 10   │ 0                  │ 1                      │ 0                   │
⋮
│ 990  │ 0                  │ 1                      │ 0                   │
│ 991  │ 0                  │ 0                      │ 1                   │
│ 992  │ 0                  │ 0                      │ 1                   │
│ 993  │ 1                  │ 0                      │ 0                   │
│ 994  │ 1                  │ 0                      │ 0                   │
│ 995  │ 0                  │ 0                      │ 1                   │
│ 996  │ 0                  │ 0                      │ 1                   │
│ 997  │ 1                  │ 0                      │ 0                   │
│ 998  │ 0                  │ 0                      │ 1                   │
│ 999  │ 1                  │ 0                      │ 0                   │
│ 1000 │ 0                  │ 1                      │ 0                   │

## Step 3: Split the data into training and test (70%-30%) 



Option 1: We can sample bernouilli RVs

In [51]:
rand()

0.2903367212909598

>**\[Exercise\]**: Train/Test (1) 

> Using Bernouilli RVs, split the data into training and test test

In [52]:
df_onehot[:train] = rand(size(df_onehot,1)) .< .7

1000-element BitArray{1}:
 false
 false
 false
  true
 false
  true
  true
  true
 false
 false
 false
  true
  true
     ⋮
  true
  true
  true
  true
  true
  true
  true
  true
  true
  true
  true
  true

In [53]:
sum(df_onehot[:train])

692

Drawback: Not exactly 70% of the data is assigned to the train set

Option 2: Select randomly exactly 70% of the whole dataset

In [17]:
using Random

In [18]:
Random.shuffle(1:size(df_onehot,1))

1000-element Array{Int64,1}:
  675
  506
   22
 1000
  586
  899
  799
  380
  496
  348
  612
  696
  286
    ⋮
  837
  901
  522
  967
  719
  222
  866
  643
  938
  920
  297
  908

In [55]:
Random.randperm(size(df_onehot,1))

1000-element Array{Int64,1}:
 824
 510
 272
 572
 969
 164
 626
  43
  38
 188
 794
 732
 561
   ⋮
 316
 899
 356
 196
 759
 914
 636
 249
 650
  87
 990
 814

>**\[Exercise\]**: Train/Test (2) 

> Using the shuffle or randperm function, split the data into training and test test

In [56]:
df_onehot[:train] = Random.randperm(size(df_onehot,1)) .<= floor(Int, size(df_onehot,1)*.7)
sum(df_onehot[:train])

700

Then divide the data into separate arrays

In [58]:
df_train = df_onehot[df_onehot[:train],:]
df_test = df_onehot[.!df_onehot[:train],:]

300×63 DataFrame. Omitted printing of 60 columns
│ Row │ CheckingAccount0DM │ CheckingAccount0-200DM │ CheckingAccountNone │
│     │ Int64⍰             │ Union{Missing, Int64}  │ Int64⍰              │
├─────┼────────────────────┼────────────────────────┼─────────────────────┤
│ 1   │ 0                  │ 1                      │ 0                   │
│ 2   │ 0                  │ 0                      │ 1                   │
│ 3   │ 0                  │ 0                      │ 1                   │
│ 4   │ 0                  │ 1                      │ 0                   │
│ 5   │ 0                  │ 1                      │ 0                   │
│ 6   │ 1                  │ 0                      │ 0                   │
│ 7   │ 0                  │ 1                      │ 0                   │
│ 8   │ 0                  │ 1                      │ 0                   │
│ 9   │ 0                  │ 0                      │ 1                   │
│ 10  │ 0                  │ 0                      │ 0                   │
⋮
│ 290 │ 1                  │ 0                      │ 0                   │
│ 291 │ 0                  │ 1                      │ 0                   │
│ 292 │ 0                  │ 0                      │ 1                   │
│ 293 │ 0                  │ 0                      │ 1                   │
│ 294 │ 1                  │ 0                      │ 0                   │
│ 295 │ 0                  │ 0                      │ 0                   │
│ 296 │ 1                  │ 0                      │ 0                   │
│ 297 │ 0                  │ 1                      │ 0                   │
│ 298 │ 0                  │ 0                      │ 1                   │
│ 299 │ 1                  │ 0                      │ 0                   │
│ 300 │ 0                  │ 0                      │ 1                   │

In [59]:
X_train = convert(Array, df_train[1:end-1])

700×62 Array{Union{Missing, Int64},2}:
 1  0  0  0   6  1  0  0  0  0  1  0  …  0  2  1  0  0  0  1  1  0  1  0  1
 1  0  0  0  42  0  1  0  0  0  0  0     0  1  1  0  0  0  2  0  1  1  0  1
 1  0  0  0  24  0  0  1  0  0  0  0     0  2  1  0  0  0  2  0  1  1  0  2
 0  0  1  0  36  0  1  0  0  0  0  1     0  1  0  1  0  0  2  1  0  1  0  1
 0  1  0  0  36  0  1  0  0  0  0  0     1  1  0  0  1  0  1  1  0  1  0  1
 0  0  1  0  12  0  1  0  0  0  1  0  …  0  1  0  1  0  0  1  0  1  1  0  1
 0  1  0  0  30  1  0  0  0  0  0  0     0  2  0  0  1  0  1  0  1  1  0  2
 1  0  0  0  48  0  1  0  0  0  0  0     1  1  1  0  0  0  1  0  1  1  0  2
 1  0  0  0  15  0  1  0  0  0  0  0     1  1  1  0  0  0  1  0  1  1  0  1
 1  0  0  0  24  0  1  0  0  0  1  0     0  1  0  1  0  0  1  0  1  1  0  2
 0  0  1  0  24  1  0  0  0  0  1  0  …  0  2  1  0  0  0  1  0  1  1  0  1
 1  0  0  0  30  0  0  0  1  0  0  0     0  3  1  0  0  0  1  0  1  1  0  1
 0  1  0  0  24  0  1  0  0  0  0  0     0  1  0 

In [60]:
y_train = df_train[:y]

700-element Array{Union{Missing, Int64},1}:
 1
 1
 2
 1
 1
 1
 2
 2
 1
 2
 1
 1
 2
 ⋮
 2
 2
 1
 2
 1
 1
 1
 1
 1
 1
 2
 1

In [61]:
X_test = convert(Array, df_test[1:14])
y_test = df_test[:y]

300-element Array{Union{Missing, Int64},1}:
 2
 1
 1
 2
 1
 2
 1
 1
 1
 2
 1
 1
 1
 ⋮
 1
 2
 1
 2
 1
 1
 1
 1
 1
 1
 1
 1

## Step 4: Best subset selection with JuMP

Ordinary least square regression with sparsity constraint
$$ \min_w \: \dfrac{1}{2} \| Y - X w \|_2^2 \quad s.t. \quad \| w \|_0 \leqslant k$$

We can linearize the cardinality constraint by introducing and extra binary variable $s\in \{ 0,1\}^p$ and big-$M$ constraints.
$$ \min_{w, s \in \{0,1\}^p} \: \dfrac{1}{2} \| Y - X w \|_2^2 \quad s.t. \quad \sum_j s_j \leqslant k, \; |w|\leqslant M s$$

In [62]:
using JuMP, Gurobi, CPLEX, LinearAlgebra

In [ ]:
function sparseRegression(X, y, k; M=10,
        verbose=true, MIPGap=1e-6, Tmax=600)

    n,p = size(X)

#     model = JuMP.Model(solver=CplexSolver(CPX_PARAM_SCRIND=1*verbose, CPX_PARAM_EPGAP=MIPGap, CPX_PARAM_TILIM=Tmax))
    model = JuMP.Model(solver=GurobiSolver(OutputFlag=1*verbose, MIPGap=MIPGap, TimeLimit=Tmax))

    #Variables
    @variable(model, w[1:p])
    @variable(model, s[i=1:p], category=:Bin)
    
    #Objective
    @objective(model, Min, LinearAlgebra.dot(y-X*w, y-X*w)/2)
    
    #Constraints
    @constraint(model, sum(s) <= k)  #sparsity
    @constraint(model, w .<= M*s)    #big-M
    @constraint(model, -w .<= M*s)   #big-M

    status = solve(model)
    
    println("Final objective value: ", getobjectivevalue(model))
    return getvalue(w), getvalue(s)
end

An easy example: $k = p$

In [ ]:
w, s = sparseRegression(X_train, y_train, 14)

Make sure the big-$M$ value is not binding

In [ ]:
w

In [ ]:
any(abs.(w) .> 10)

The solution is trivial

In [ ]:
s

In [ ]:
LinearAlgebra.norm(w - inv(X_train'*X_train)*(X_train'*y_train))

In [ ]:
println("Out-of-sample performance: ", LinearAlgebra.norm(X_test*w - y_test)^2/2)

Another example

In [ ]:
w, s = sparseRegression(X_train, y_train, 5)

In [ ]:
w

In [ ]:
s

In [ ]:
println("Out-of-sample performance: ", norm(X_test*w - y_test)^2/2)

## Step 4: Benchmark against existing methods
Another widely-used feature selection method is the Lasso, implemented in the glmnet package

In [ ]:
using RCall